### ISSUE TITLE
DD_SERVICE env variable isn't respected for ddtrace

### ISSUE THREAD

**Issue by driv3r** [DataDog/datadog-lambda-layer-rb#22]
## Expected Behavior

`DD_SERVICE` environment variable should take precedence over `AWS_LAMBDA_FUNCTION_NAME` for APM service name based on [`ddtrace` documentation](https://github.com/DataDog/dd-trace-rb/blob/df4c39b60a82fb33994b582a96b1696de35fe008/docs/GettingStarted.md). 

It already works like this in `datadog-lambda-layer-js`

## Actual Behavior

`DD_SERVICE` environment variable is ignored. I assume it's because [lambda layer hard codes it to function name](https://github.com/DataDog/datadog-lambda-layer-rb/blob/8e717fcb6205a3f797f2ad8cd1a468efdb598411/lib/datadog/lambda/trace/listener.rb#L50).  

I'm wondering if it would be straightforward to have it configured during ddtrace configuration [here](https://github.com/DataDog/datadog-lambda-layer-rb/blob/8e717fcb6205a3f797f2ad8cd1a468efdb598411/lib/datadog/lambda.rb#L27-L41) instead of hardcoding.
 
## Steps to Reproduce the Problem

  1. Create ruby lambda function with name `dd-test` with environment variable `DD_SERVICE=dd-new-name`
  1. Instrument with `ddtrace`  and `datadog-lambda` gems
  1. APM will show service named `dd-test` instead of `dd-new-name`

## Specifications

  - Datadog Lambda gem version: 0.7.0
  - ddtrace gem version: 0.36.0
  - Ruby version: 2.7

**Comment by tianchu** [comment]
This is because Datadog tracer is not yet supported for Ruby. The recommended way to customize `service` name for serverless services is tagging the Lambda function with a `service` tag https://docs.datadoghq.com/integrations/amazon_lambda/?tab=nodejs#the-service-tag

**Comment by tianchu** [comment]
Hi @driv3r, thanks for reporting this issue, we will take a deeper look at why the `DD_SERVICE` is not working. However, for serverless we do recommend people tag their Lambda functions directly with a `service` tag instead of using `DD_SERVICE` environment variable to customize the service name  https://docs.datadoghq.com/integrations/amazon_lambda/?tab=nodejs#the-service-tag. Can you give it a shot (please make sure your [forwarder](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring) is updated to the latest version)?
